on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"
      - run: terraform init -backend=false
      - run: terraform fmt -check
      - run: terraform workspace select -or-create=true 012345678901_us-east-1_stack
      - run: terraform validate -no-color
